### ISSUE TITLE
New Rule: Directory Structure

### ISSUE THREAD

**Issue by Jeehut** [JamitLabs/ProjLint#16]
A rule that allows to specify how the files in a directory should be structured and what kind of files are allowed. An example configuration could look something like this:

```yaml
- rules:
  - directory_structure:
      - App/Sources:
          apply_to_subfolders: true
          allowed_files_regex: ".*\\.swift"
      - App/Sources/Extensions:
          apply_to_subfolders: true
          allowed_files_regex: ".*Extension\\.swift"
      - App/SupportingFiles:
          apply_to_subfolders: true
          disallowed_files_regex: ".*\\.swift"
```
