### ISSUE TITLE
New Rule: File Name Regex

### ISSUE THREAD

**Issue by Jeehut** [JamitLabs/ProjLint#20]
It should be possible to define for specific folders or specific type extensions, what the file name should be structured like. A config could look something like this:

```
rules:
  - file_name_regex:
      - directory_content_matching:
          Sources/Extensions: "\A[A-Z]\S+Extension\.swift"
      - directory_content_not_matching:
          Sources/SupportingFiles: "\A.*\.swift\z"
      - type_extension_matching:
          swift: "\A[A-Z]\S+\.swift\z"
          plist: "\A[A-Z]\S+.plist\z"
```
