### ISSUE TITLE
Add Shared Variables to Configuration File

### ISSUE THREAD

**Issue by Jeehut** [JamitLabs/ProjLint#4]
There should be a way to specify shared variables within the configuration file which can be referenced in all String option entries (like paths or regexes). The structure might look like the following:
```
shared_variables:
  project_name: MyProject
  main_scheme: MyApp
```

Then a String can use this variable with something like this:

```
rules:
  - file_existence:
      existing_paths:
        - {{project_name}}.xcproj/project.pbxproj
```
