### ISSUE TITLE
New Rule: Git Message Regex

### ISSUE THREAD

**Issue by Jeehut** [JamitLabs/ProjLint#7]
A rule that allows to check git messages in specified branches (also defineable through regexes) using regexes. An example configuration could be something like this:

```yaml
rules:
  - git_message_regex:
      branch: work/.*
      last_commits_count: 10
      matching: "\\A(?:\\[[^\\]]+\\] )?[A-Z](?:.){,49}(?:\\n\\n\\S.*)?\\z"
```

Whereas the `branch` value `active` could always only lint the active branch.

In combination with [Overcommit](https://github.com/brigade/overcommit) (which could run ProjLint before committing) this rule would be even useful during development.
